name: multiple_image_picker_widget
description: better image picker widget for multi pick
version: 0.0.1
repository: https://github.com/halfmoon-mind/multiple-image-picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^2.6.0
  intl: ^0.18.1
  get: ^4.6.5
  dropdown_button2: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

